### ISSUE TITLE
Save spec yaml as rds and include?

### ISSUE THREAD

**Issue by richfitz** [richfitz/stevedore#17]
Each spec takes only 50-70kb (compared with 250-350kb for the raw yaml) so this might be worthwhile

**Comment by richfitz** [comment]
This would mean that the patching would be done at build time not run time too, and potentially remove the yaml dependency. The downside is that the package will get largish as the number of spec versions continues to grow

**Comment by nuest** [comment]
How many specs do you expect to support at the same time?

**Comment by richfitz** [comment]
Currently it supports all of 1.25 through 1.36 (though none are included in the package).  There's no real need to limit support that I can see apart from the space of keeping them all around!

Putting all the spec files into the package would be nice (because then the user does not have to download them) but there is an option (`stevedore.spec.path`) that can be used to cache these across sessions.

**Comment by richfitz** [comment]
Compressing the spec with gzip also reduces the size to ~50k

**Comment by richfitz** [comment]
> Packages should be of the minimum necessary size. Reasonable compression should be used for data (not just .rda files) and PDF documentation: CRAN will if necessary pass the latter through qpdf.
As a general rule, neither data nor documentation should exceed 5MB (which covers several books). A CRAN package is not an appropriate way to distribute course notes, and authors will be asked to trim their documentation to a maximum of 5MB.

> Where a large amount of data is required (even after compression), consideration should be given to a separate data-only package which can be updated only rarely (since older versions of packages are archived in perpetuity).

> Similar considerations apply to other forms of “data”, e.g., .jar files.

**Comment by nuest** [comment]
Have you considered a seperate package? `stevedore.specs`
This way you could always ship the "latest" (or "most common" one) with the package, but have all others accessible on demand... although on demand also is the case now when they are downloaded from the Docker website.

**Comment by richfitz** [comment]
I just added all the specs. It's only 500k when compressed with bzip2 so should be fine
