### ISSUE TITLE
Add support for docker cp

### ISSUE THREAD

**Issue by nuest** [richfitz/stevedore#40]
To extract single files from a container, add support for the [`docker cp`](https://docs.docker.com/engine/reference/commandline/cp/) (copy) instruction.

@richfitz Can you outline the required steps for this? The readme just say this is "major work", but still I hope this issue helps by collecting some :+1:s  :-)

[fyi: just switched from harbor to stevedore to leverage DinD, so running R within a container and start other containers - works like a charm]

**Comment by richfitz** [comment]
This is done on a branch!  Can you try the code here please: https://github.com/richfitz/stevedore/tree/i37_cp

**Comment by richfitz** [comment]
See here https://github.com/richfitz/stevedore/compare/i37_cp#diff-6a75c27f5b4d87034453fcfc7333e046R1161 in the tests for examples for now - I need to propagate this to the vignette

The python client doesn't support this and I can now see why!

**Comment by nuest** [comment]
Will try to squeeze some testing in... anyways, this is a duplicate of #37
