### ISSUE TITLE
possible validation error in binding ports?

### ISSUE THREAD

**Issue by cboettig** [richfitz/stevedore#45]
I tried to bind a port explicitly to `127.0.0.1`, (which I believe can be useful when I'm only accessing the app from the host and want to be sure I'm not exposing it to my network).  Unfortunately this seems to throw an error in validation: 

```
Port binding '127.0.0.1:5000:5000' does not not match '[<host>:]<container>'
```

**Comment by richfitz** [comment]
Thanks Carl - this should be fixed as of 9c402cd (branch `develop`) now
