### ISSUE TITLE
Option UNIX_SOCKET_PATH (10231) not supported.

### ISSUE THREAD

**Issue by ilarischeinin** [richfitz/stevedore#48]
`stevedore` used to work just fine for me (and is a tremendous package by the way, so thank you!). However, nowadays I only get the following error when I try to use it:

```sh
R --vanilla
```
``` r
library(stevedore)
docker_client()
#> Error in curl::handle_setopt(h, .list = opts): Option UNIX_SOCKET_PATH (10231) not supported.
```

This is with R 3.6.0 on macOS Mojave 10.14.6 and Docker Desktop 2.1.0.1 (37199), and below is rest of my `sessionInfo()`. I'm more than happy to provide any pieces of information that might be helpful in debugging, and to try anything that might help solve this. But I don't really know what I should try. I have removed and reinstalled `stevedore`, but that didn't help.

Since it's related to the socket, I checked this and that the file exists:

``` r
capabilities("sockets")
#> sockets 
#>    TRUE
```

```
$ ls -l /var/run/docker.sock 
lrwxr-xr-x  1 root  daemon  74 Aug 19 15:47 /var/run/docker.sock -> /Users/ilarischeinin/Library/Containers/com.docker.docker/Data/docker.sock
$ ls -l /Users/ilarischeinin/Library/Containers/com.docker.docker/Data/docker.sock
srwxr-xr-x  1 ilarischeinin  staff  0 Aug 19 15:47 /Users/ilarischeinin/Library/Containers/com.docker.docker/Data/docker.sock
```

All `docker` commands work just fine from the command line (i.e. I can run containers, pull images, etc just fine).

```
R version 3.6.0 (2019-04-26)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.6

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] stevedore_0.9.1

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.2      ps_1.3.0        digest_0.6.20   R6_2.4.0       
 [5] reprex_0.3.0    evaluate_0.14   rlang_0.4.0     curl_4.0       
 [9] fs_1.3.1        callr_3.3.1     whisker_0.3-2   rmarkdown_1.14 
[13] tools_3.6.0     xfun_0.8        compiler_3.6.0  processx_3.4.1 
[17] clipr_0.7.0     htmltools_0.3.6 knitr_1.24     
```

**Comment by richfitz** [comment]
Thank you for the report - this is due to changes in the `curl` package (issue https://github.com/jeroen/curl/issues/192 - @jeroen knows about it).

The workaround is to install a previous version of curl I am afraid.  On a different project I have done this on travis as https://github.com/mrc-ide/odin.ui/blob/master/.travis.yml#L22-L23

Any version prior to the current should work

**Comment by jeroen** [comment]
I'm sorry I haven't gotten to this yet, it will be fixed for the next release of `curl`!

**Comment by richfitz** [comment]
Thanks @jeroen :pray:

**Comment by jeroen** [comment]
Could you test if this is fixed in the devel version of curl?

```r
remotes::install_github("jeroen/curl")
```

**Comment by ilarischeinin** [comment]
Works for me! And to my eyes it looks like travis passes too (at least the vignette building step that seemed to give an error earlier).

Thank you @richfitz and @jeroen!

**Comment by richfitz** [comment]
Yup, this fix works on travis - https://travis-ci.org/richfitz/stevedore/builds/577334116, but unfortunately it looks like we're being bitten by something related to #46 (nothing to do with curl, and something I'll have a look at)
