### ISSUE TITLE
How to specify shm size ?

### ISSUE THREAD

**Issue by fvalenduc** [richfitz/stevedore#66]
Is there a way to specify the size of the shared memory when starting a container with docker$container$run ?
With the command line, that would be docker run ... --shm-size...
I tried to find this option in the documentation but without success. 
Sorry If my question as already been answered somewhere else.

**Comment by richfitz** [comment]
This appears not to be documented, nor do I have a full example of it working - but some pointers:

* https://richfitz.github.io/stevedore/reference/docker_container_collection.html
* modify the `host_config` argument here, following the underlying SDK docs here: https://docs.docker.com/engine/api/v1.43/#tag/Container/operation/ContainerCreate

It might look like passing:

```
host_config = list(ShmSize = jsonlite::unbox(10000000))
```

through to container creation or run. See [this test](https://github.com/richfitz/stevedore/blob/master/tests/testthat/test-docker-client-containers.R#L705-L707) for a similar example

**Comment by fvalenduc** [comment]
Indeed, host_config = list(ShmSize = jsonlite::unbox(10000000)) works perfectly well.
Thanks for your rapid anwser.
