### ISSUE TITLE
Pick and add a default spec file to the package

### ISSUE THREAD

**Issue by richfitz** [richfitz/stevedore#7]
1.29 has been good so far, but probably should track the newer versions

**Comment by richfitz** [comment]
1.35 is out now: https://docs.docker.com/engine/api/v1.35/

**Comment by richfitz** [comment]
Support for up to 1.36 now included but without easy access to release dates it's not really clear what version we should add - it can't be too high because otherwise daemons will balk at running it...

**Comment by richfitz** [comment]
Interacts with #17

**Comment by richfitz** [comment]
1.30 is required for the configs endpoints to work

**Comment by nuest** [comment]
I assume this might also help with my current ... little annoyance: I'm switching my package from harbor to stevedore, and regularly get errors:

```
Error: Test failed: 'an R script can be created with resources of the same folder '
* File does not exist: /tmp/RtmpwRcyhO/stevedore_spec_58f1d4ae23c/v1.29.yaml
1: stevedore::docker_client() at :13
2: docker_api_client(config)
3: docker_api_client_data(self$http_client$api_version, config$quiet)
4: swagger_spec_read(version, quiet)
5: hash_file(path_yml)
6: assert_file_exists(files)
7: stop(ngettext(length(msg), "File does not exist: ", "Files do not exist: "), paste(msg, collapse = ", "))
```
I assume this is because the tempdir is cleaned/changed by the session restarting in RStudio. Long story short:

What do you think about _adding a fallback mechanism (with a warning) to use the included spec file if no cache and no remote can be found_?

**Comment by richfitz** [comment]
I've not seen that error before - is that operating within `R CMD check` perhaps?

Thanks for the feedback. You're absolutely right that this needs dealing with. I've been exploring how to include more than a couple in the package and I think I can support a number after applying some compression.  The current approach is super flakey in any case and needs fixing!

The issue is that if the client accesses an API version ahead of the server the server responds with a 400 and instruction to downgrade. However, docker api work seems to have slowed at last and 1.37 has been the maximum supported api version since ~april

**Comment by nuest** [comment]
Yes, the error appears as part of `R CMD check` and as well while running tests with `testthat`, in combination with using RStudio's "build and reload" feature, which relies on `devtools` AFAIK.

**Comment by richfitz** [comment]
@nuest - can you please try the [i7_include_spec](https://github.com/richfitz/stevedore/tree/i7_include_spec) branch, which includes a fix for this. If you want to match versions, please try `docker_client(api_version = "detect")`
